### ISSUE TITLE
Various warnings and error running tests on Mac Catalina

### ISSUE THREAD

**Issue by jandyman** [JuliaPlots/MakieGallery.jl#205] opened 2020-02-08 19:18 UTC
In case it is helpful, I'm attaching the output of testing the Makie package on MacOS catalina. There are various errors and warnings.

[TestingMakie.txt](https://github.com/JuliaPlots/MakieGallery.jl/files/4175019/TestingMakie.txt)

**Comment by asinghvi17** [comment] 2020-02-08 20:40
Could you try this on the latest master of MakieGallery, AbstractPlotting and GLMakie?  I think these warnings should already have been fixed there (though I could be mistaken). 

You can get the master branches by running this snippet of code in the REPL:
```julia
]add MakieGallery#master AbstractPlotting#master GLMakie#master
```

**Comment by jandyman** [comment] 2020-02-09 01:14
I followed the instructions above. There are fewer errors, I've attached the output
[TestingMakie.txt](https://github.com/JuliaPlots/MakieGallery.jl/files/4176344/TestingMakie.txt)

**Comment by asinghvi17** [comment] 2020-02-09 01:19
Could you post the images at `$(dirname(pathof(MakieGallery)))/../test/tested_different/isorange,_isovalue`?  

they should be in the `test/tested_different` folder of the MakieGallery repo.  That's the only concerning failure, since we're now seeing this across multiple machines, but not on CI (cc @SimonDanisch here, is there something different on the CI setup?).

The rest of the warnings are more or less intended, and the result should be unaffected.

Thanks a lot!

**Comment by asinghvi17** [comment] 2020-02-09 01:21
For reference, we get these warnings on CI, and the images are generated essentially correctly.  These weren't in the log above, but the example seems to have failed silently.

```
Running isorange,_isovalue
 ┌ Warning: OpenGL call to glUniform1i, with arguments: ("5", "3")
 │                 Failed with error: GL_INVALID_OPERATION.
 └ @ ModernGL /builds/JuliaGPU/MakieGallery-jl/.julia/packages/ModernGL/rVuW2/src/functionloading.jl:22
 ┌ Warning: OpenGL call to glUniform1i, with arguments: ("5", "3")
 │                 Failed with error: GL_INVALID_OPERATION.
 └ @ ModernGL /builds/JuliaGPU/MakieGallery-jl/.julia/packages/ModernGL/rVuW2/src/functionloading.jl:22
┌ Warning: OpenGL call to glUniform3fv, with arguments: ("7", "1", "Float32[0.25, 1.0, 3.0]")
 │                 Failed with error: GL_INVALID_OPERATION.
 └ @ ModernGL /builds/JuliaGPU/MakieGallery-jl/.julia/packages/ModernGL/rVuW2/src/functionloading.jl:22
 ┌ Warning: OpenGL call to glUniform1i, with arguments: ("5", "3")
 │                 Failed with error: GL_INVALID_OPERATION.
 └ @ ModernGL /builds/JuliaGPU/MakieGallery-jl/.julia/packages/ModernGL/rVuW2/src/functionloading.jl:22
┌ Warning: OpenGL call to glUniform3fv, with arguments: ("7", "1", "Float32[0.25, 1.0, 3.0]")
 │                 Failed with error: GL_INVALID_OPERATION.
 └ @ ModernGL /builds/JuliaGPU/MakieGallery-jl/.julia/packages/ModernGL/rVuW2/src/functionloading.jl:22
```

**Comment by jandyman** [comment] 2020-02-09 16:48
> Could you post the images at `$(dirname(pathof(MakieGallery)))/../test/tested_different/isorange,_isovalue`?
> 
> they should be in the `test/tested_different` folder of the MakieGallery repo. That's the only concerning failure, since we're now seeing this across multiple machines, but not on CI (cc @SimonDanisch here, is there something different on the CI setup?).
> 
> The rest of the warnings are more or less intended, and the result should be unaffected.
> 
> Thanks a lot!

I'd be happy to, but I'm not sure where I would evaluate that expression. It doesn't appear to be a unix shell command or a Julia REPL command. Forgive me, I'm new to Atom and Julia.

**Comment by asinghvi17** [comment] 2020-02-09 16:51
In the Julia REPL, you can probably just do something like:
```
using MakieGallery

;open $(dirname(pathof(MakieGallery)))/../test/tested_different/
```
Here, the `;` at the start puts the REPL into "shell mode", which essentially mimics the system shell (with some limitations).

The command will open a Finder window in the `tested_different` directory.

**Comment by jandyman** [comment] 2020-02-09 16:54
shell> ;open $(dirname(pathof(MakieGallery)))/../test/tested_different/
ERROR: UndefVarError: MakieGallery not defined
Stacktrace:
 [1] top-level scope at none:0

**Comment by jandyman** [comment] 2020-02-09 16:56
It doesn't look like MakieGallery was even installed. I just installed Makie and MakieLayout, per instructions.

**Comment by asinghvi17** [comment] 2020-02-09 16:58
You should still have it installed if you executed this snippet:
```
]add MakieGallery#master AbstractPlotting#master GLMakie#master
```

and even if not, it would have been downloaded as a test dependency of Makie.  In that case, could you poke around in `~/.julia/packages/MakieGallery/`?

**Comment by jandyman** [comment] 2020-02-09 17:06
oops, I assumed that MakieGallery was not installed because of this:

julia> Using MakieGallery
ERROR: syntax: extra token "MakieGallery" after end of expression

list of files in ~/.julia/packages/MakieGallery/ is attached
[filelist.txt](https://github.com/JuliaPlots/MakieGallery.jl/files/4177191/filelist.txt)

**Comment by jandyman** [comment] 2020-02-09 17:08
Just noticed I accidentally capitalized "Using". 

But now I get this:

shell> ;open $(dirname(pathof(MakieGallery)))/../test/tested_different/
zsh:1: command not found: ;open

But I sent the file list, so it probably doesn't matter

**Comment by asinghvi17** [comment] 2020-02-09 17:28
Oh, my mistake - I'd thought you were testing MakieGallery, not Makie.  Could you snoop around in `~/.julia/packages/Makie` for a `test/tested_different` folder?

**Comment by jandyman** [comment] 2020-02-09 17:34
![ref_image](https://user-images.githubusercontent.com/7635406/74106871-b161b600-4b27-11ea-9ef8-ad6f58733b3d.jpg)
![test_image](https://user-images.githubusercontent.com/7635406/74106872-b292e300-4b27-11ea-9542-f42d11a378a7.jpg)

**Comment by asinghvi17** [comment] 2020-02-09 17:35
Ahh, there's the problem.  This happens on my system as well - I'll try to debug the cause today or tomorrow.  Thanks for the report!

**Comment by jandyman** [comment] 2020-02-09 17:36
You are welcome. This looks like a great package so I'm happy to help.

**Comment by asinghvi17** [comment] 2020-02-15 18:33
I think we have found a solution to the isorange problem, it should be merged into AbstractPlotting in the next week or so.  Thanks for all the help, feel free to ask more questions if you need to!

**Closed by asinghvi17** 2020-02-15 18:33 UTC
Labels: CI, bug
